package com.sopiana.yang.javaDecompiler.instruction;

public enum opcodeTable 
{
	_aconst_null((byte)0x01,"aconst_null"),
	_iconst_m1	((byte)0x02,"iconst_m1"),
	_iconst_0	((byte)0x03,"iconst_0"),
	_iconst_1	((byte)0x04,"iconst_1"),
	_iconst_2	((byte)0x05,"iconst_2"),
	_iconst_3	((byte)0x06,"iconst_3"),
	_iconst_4	((byte)0x07,"iconst_4"),
	_iconst_5	((byte)0x08,"iconst_5"),
	_fconst_0	((byte)0x0b,"fconst_0"),
	_fconst_1	((byte)0x0c,"fconst_1"),
	_fconst_2	((byte)0x0d,"fconst_2"),
	_dconst_0	((byte)0x0e,"dconst_0"),
	_dconst_1	((byte)0x0f,"dconst_1"),
	_bipush		((byte)0x10,"bipush"),
	_fload		((byte)0x17,"fload"),
	_dload		((byte)0x18,"dload"),
	_aload		((byte)0x19,"aload"),
	_fload_0	((byte)0x22,"fload_0"),
	_fload_1	((byte)0x23,"fload_1"),
	_fload_2	((byte)0x24,"fload_2"),
	_fload_3	((byte)0x25,"fload_3"),
	_dload_0	((byte)0x26,"dload_0"),
	_dload_1	((byte)0x27,"dload_1"),
	_dload_2	((byte)0x28,"dload_2"),
	_dload_3	((byte)0x29,"dload_3"),
	_aload_0	((byte)0x2a,"aload_0"),
	_aload_1	((byte)0x2b,"aload_1"),
	_aload_2	((byte)0x2c,"aload_2"),
	_aload_3	((byte)0x2d,"aload_3"),
	_iaload		((byte)0x2e,"iaload"),
	_faload		((byte)0x30,"faload"),
	_daload		((byte)0x31,"daload"),
	_aaload		((byte)0x32,"aaload"),
	_baload		((byte)0x33,"baload"),
	_caload		((byte)0x34,"caload"),
	_fstore		((byte)0x38,"fstore"),
	_dstore		((byte)0x39,"dstore"),
	_astore		((byte)0x3a,"astore"),
	_fstore_0	((byte)0x43,"fstore_0"),
	_fstore_1	((byte)0x44,"fstore_1"),
	_fstore_2	((byte)0x45,"fstore_2"),
	_fstore_3	((byte)0x46,"fstore_3"),
	_dstore_0	((byte)0x47,"dstore_0"),
	_dstore_1	((byte)0x48,"dstore_1"),
	_dstore_2	((byte)0x49,"dstore_2"),
	_dstore_3	((byte)0x4a,"dstore_3"),
	_astore_0	((byte)0x4b,"astore_0"),
	_astore_1	((byte)0x4c,"astore_1"),
	_astore_2	((byte)0x4d,"astore_2"),
	_astore_3	((byte)0x4e,"astore_3"),
	_iastore	((byte)0x4f,"iastore"),
	_fastore	((byte)0x51,"fastore"),
	_dastore	((byte)0x52,"dastore"),
	_aastore	((byte)0x53,"aastore"),
	_bastore	((byte)0x54,"bastore"),
	_castore	((byte)0x55,"castore"),
	_dup		((byte)0x59,"dup"),
	_dup_x1		((byte)0x5a,"dup_x1"),
	_dup_x2		((byte)0x5b,"dup_x2"),
	_dup2		((byte)0x5c,"dup2"),
	_dup2_x1	((byte)0x5d,"dup2_x1"),
	_dup2_x2	((byte)0x5e,"dup2_x2"),
	_iadd		((byte)0x60,"iadd"),
	_fadd		((byte)0x62,"fadd"),
	_dadd		((byte)0x63,"dadd"),
	_fsub		((byte)0x66,"fsub"),
	_dsub		((byte)0x67,"dsub"),
	_fmul		((byte)0x6a,"fmul"),
	_dmul		((byte)0x6b,"dmul"),
	_idiv		((byte)0x6c,"idiv"),
	_fdiv		((byte)0x6e,"fdiv"),
	_ddiv		((byte)0x6f,"ddiv"),
	_frem		((byte)0x72,"frem"),
	_drem		((byte)0x73,"drem"),
	_fneg		((byte)0x76,"fneg"),
	_dneg		((byte)0x77,"dneg"),
	_iand		((byte)0x7e,"iand"),
	_i2l		((byte)0x85,"i2l"),
	_i2f		((byte)0x86,"i2f"),
	_i2d		((byte)0x87,"i2d"),
	_f2i		((byte)0x8b,"f2i"),
	_f2l		((byte)0x8c,"f2l"),
	_f2d		((byte)0x8d,"f2d"),
	_d2i		((byte)0x8e,"d2i"),
	_d2l		((byte)0x8f,"d2l"),
	_d2f		((byte)0x90,"d2f"),
	_i2b		((byte)0x91,"i2b"),
	_i2c		((byte)0x92,"i2c"),
	_i2s		((byte)0x93,"i2s"),
	_fcmpl		((byte)0x95,"fcmpl"),
	_fcmpg		((byte)0x96,"fcmpg"),
	_dcmpl		((byte)0x97,"dcmpl"),
	_dcmpg		((byte)0x98,"dcmpg"),
	_if_icmpeq	((byte)0x9f,"if_icmpeq"),
	_if_icmpne	((byte)0xa0,"if_icmpne"),
	_if_icmplt	((byte)0xa1,"if_icmplt"),
	_if_icmpge	((byte)0xa2,"if_icmpge"),
	_if_icmpgt	((byte)0xa3,"if_icmpgt"),
	_if_icmple	((byte)0xa4,"if_icmple"),
	_if_acmpeq	((byte)0xa5,"if_acmpeq"),
	_if_acmpne	((byte)0xa6,"if_acmpne"),
	_goto		((byte)0xa7,"goto"),
	_freturn	((byte)0xae,"freturn"),
	_dreturn	((byte)0xaf,"dreturn"),
	_areturn	((byte)0xb0,"areturn"),
	_getstatic	((byte)0xb2,"getstatic"),
	_getfield	((byte)0xb4,"getfield"),
	_anewarray	((byte)0xbd,"anewarray"),
	_arraylength((byte)0xbe,"arraylength"),
	_athrow		((byte)0xbf,"athrow"),
	_checkcast	((byte)0xc0,"checkcast"),
	_goto_w		((byte)0xc8,"goto_w");
	public byte opcode;
	public String mnemonic;
	private opcodeTable(byte opcode,String mnemonic)
	{
		this.opcode = opcode;
		this.mnemonic = mnemonic;
	}
}
